apiVersion: v1
kind: Service
metadata:
  name: ole-cube-core-service
spec:
  type: LoadBalancer
  selector:
    app: ole-cube-core
  ports:
    - name: http
      port: 4000
      targetPort: 4000
    - name: sql
      port: 15432
      targetPort: 15432